# Generated by Django 2.2.5 on 2019-09-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(choices=[(1, 'Younger'), (2, 'Young'), (3, 'Middle'), (4, 'Middle_plus'), (5, 'Old')], default=1)),
                ('height', models.IntegerField(choices=[(1, 'Tall'), (2, 'Average'), (3, 'Short')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooting', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Average'), (3, 'Developing')], default=1)),
                ('Dibbling', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Average'), (3, 'Developing')], default=1)),
                ('passing', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Average'), (3, 'Developing')], default=1)),
                ('rebounding', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Average'), (3, 'Developing')], default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
    ]
