# Generated by Django 2.2.5 on 2019-09-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('team', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='Dibbling',
            new_name='defense',
        ),
    ]
