# Generated by Django 2.2.5 on 2019-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190919_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=2),
        ),
    ]
