# Generated by Django 2.2.5 on 2019-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191014_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='defense',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='skills',
            name='passing',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='skills',
            name='rebounding',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='skills',
            name='shooting',
            field=models.IntegerField(default=2),
        ),
    ]
